mod about;
mod debug;
mod devices;
mod installation;
mod logs;
mod new_version_popup;
mod notifications;
mod settings;
mod settings_controls;
mod setup_wizard;
mod statistics;

pub use about::*;
pub use debug::*;
pub use devices::*;
pub use installation::*;
pub use logs::*;
pub use new_version_popup::*;
pub use notifications::*;
pub use settings::*;
pub use settings_controls::*;
pub use setup_wizard::*;
pub use statistics::*;
