[package]
name = "shared"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

build = "build.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
backtrace = "0.3"
glam = { version = "0.30", features = ["serde"] }
log = "0.4"
parking_lot = "0.12"
paste = "1"
serde = { version = "1", features = ["derive"] }
settings-schema = { git = "https://github.com/alvr-org/settings-schema-rs", rev = "676185f" }
# settings-schema = { path = "../../../../settings-schema-rs/settings-schema" }

[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.14"

[build-dependencies]
vergen-git2 = { version = "1.0.7", features = ["build"] }
