#ifndef NANVRCLIENT_PACKETTYPES_H
#define NANVRCLIENT_PACKETTYPES_H
#include "../nanvr_server/bindings.h"
#include <assert.h>
#include <stdint.h>

enum NANVR_CODEC {
    NANVR_CODEC_H264 = 0,
    NANVR_CODEC_HEVC = 1,
    NANVR_CODEC_AV1 = 2,
};

enum NANVR_H264_PROFILE {
    NANVR_H264_PROFILE_HIGH = 0,
    NANVR_H264_PROFILE_MAIN = 1,
    NANVR_H264_PROFILE_BASELINE = 2,
};

enum NANVR_RATE_CONTROL_METHOD {
    NANVR_CBR = 0,
    NANVR_VBR = 1,
};

enum NANVR_ENTROPY_CODING {
    NANVR_CABAC = 0,
    NANVR_CAVLC = 1,
};

enum NANVR_ENCODER_QUALITY_PRESET { NANVR_QUALITY = 0, NANVR_BALANCED = 1, NANVR_SPEED = 2 };

enum NANVR_INPUT {
    NANVR_INPUT_FINGER_INDEX,
    NANVR_INPUT_FINGER_MIDDLE,
    NANVR_INPUT_FINGER_RING,
    NANVR_INPUT_FINGER_PINKY,
};
#define NANVR_BUTTON_FLAG(input) (1ULL << input)

#endif // NANVRCLIENT_PACKETTYPES_H
